# Generated by Django 4.2.5 on 2023-09-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'communities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonPushableData',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('procedure_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_group_en', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_date', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property_sub_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('property_sub_type_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property_usage_en', models.BooleanField(blank=True, null=True)),
                ('reg_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_type_en', models.CharField(blank=True, max_length=255, null=True)),
                ('area_id', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('project_number', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('master_project_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_landmark_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_metro_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_mall_en', models.CharField(blank=True, max_length=255, null=True)),
                ('rooms_en', models.CharField(blank=True, max_length=255, null=True)),
                ('has_parking', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_area', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_worth', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_sale_price', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_value', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_rent_price', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_parties_role_1', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_parties_role_2', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_parties_role_3', models.CharField(blank=True, max_length=255, null=True)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'non_pushable_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('prop_area', models.FloatField(blank=True, null=True)),
                ('reg_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rooms', models.CharField(blank=True, max_length=255, null=True)),
                ('residential', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertySubtype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('main_type', models.CharField(blank=True, max_length=255, null=True)),
                ('main_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'property_subtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_buildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCommunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(blank=True, max_length=255, null=True)),
                ('community', models.CharField(blank=True, max_length=255, null=True)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('fixed_area_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_communities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_group_en', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_date', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property_sub_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('property_sub_type_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property_usage_en', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_type_en', models.CharField(blank=True, max_length=255, null=True)),
                ('area_id', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('project_number', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('master_project_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_landmark_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_metro_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_mall_en', models.CharField(blank=True, max_length=255, null=True)),
                ('rooms_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('rooms_en', models.CharField(blank=True, max_length=255, null=True)),
                ('has_parking', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_area', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_worth', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_sale_price', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_value', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_rent_price', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_parties_role_1', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_parties_role_2', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_parties_role_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'raw_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reg_type', models.CharField(blank=True, max_length=255, null=True)),
                ('usage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionSubtype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('main_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transaction_subtype',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='non_pushable_data',
        ),
    ]
