# Generated by Django 4.2.5 on 2023-09-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_areas_communities_nonpushabledata_projects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.DeleteModel(
            name='PropertySubtype',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='TransactionSubtype',
        ),
    ]
